### ISSUE TITLE
can't build with prod or aot flag ... Compatibility flaw with Angular 5

### ISSUE THREAD

**Issue by dewolft** [goergch/angular2-qrscanner#37]
Hello Everyone,

since i've updated to Angular 5, when i get to build with --aot or --prod flag i get this error : 

ERROR in ./node_modules/angular2-qrscanner/src/qrscanner.component.ngfactory.ts
Module build failed: Error: D:\Workplace\dancematik\node_modules\angular2-qrscanner\src\qrscanner.component.ngfactory.ts is missing from the TypeScript compilation. Please make sure
it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\Workplace\dancematik\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:662:23)
    at plugin.done.then (D:\Workplace\dancematik\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
 @ ./src/app/leggiticket/leggiticket.component.ngfactory.js 8:0-97
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts

As far as you know... there is some issue with this component and Angular 5 ?

i've tried also the vNext branch... but i get the same issue...

**Comment by dewolft** [comment]
hello! :) 

someone have found a solution for this issue? i can do something for workaround it?
